// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
  Address,
  DataSourceTemplate,
  DataSourceContext
} from "@graphprotocol/graph-ts";

export class WeightedPool extends DataSourceTemplate {
  static create(address: Address): void {
    DataSourceTemplate.create("WeightedPool", [address.toHex()]);
  }

  static createWithContext(address: Address, context: DataSourceContext): void {
    DataSourceTemplate.createWithContext(
      "WeightedPool",
      [address.toHex()],
      context
    );
  }
}

export class StablePool extends DataSourceTemplate {
  static create(address: Address): void {
    DataSourceTemplate.create("StablePool", [address.toHex()]);
  }

  static createWithContext(address: Address, context: DataSourceContext): void {
    DataSourceTemplate.createWithContext(
      "StablePool",
      [address.toHex()],
      context
    );
  }
}

export class ConvergentCurvePool extends DataSourceTemplate {
  static create(address: Address): void {
    DataSourceTemplate.create("ConvergentCurvePool", [address.toHex()]);
  }

  static createWithContext(address: Address, context: DataSourceContext): void {
    DataSourceTemplate.createWithContext(
      "ConvergentCurvePool",
      [address.toHex()],
      context
    );
  }
}

export class LiquidityBootstrappingPool extends DataSourceTemplate {
  static create(address: Address): void {
    DataSourceTemplate.create("LiquidityBootstrappingPool", [address.toHex()]);
  }

  static createWithContext(address: Address, context: DataSourceContext): void {
    DataSourceTemplate.createWithContext(
      "LiquidityBootstrappingPool",
      [address.toHex()],
      context
    );
  }
}
